### ISSUE TITLE
点击候选人详细信息中的评论 Chip 时出现栈溢出

### ISSUE THREAD

**Issue by Enter-tainer** [UniqueStudio/UniqueRecruitmentDashboard#15]
点击被码掉的 Chip 时，控制台出现栈溢出的报错
![image](https://user-images.githubusercontent.com/25521218/85426786-84311400-b5ad-11ea-809e-cada2d87cb0c.png)

![image](https://user-images.githubusercontent.com/25521218/85426855-990da780-b5ad-11ea-8d4a-c84c907907ea.png)

出错位置的代码与焦点相关

![image](https://user-images.githubusercontent.com/25521218/85426926-afb3fe80-b5ad-11ea-85e9-710478962944.png)

猜测与 https://github.com/mui-org/material-ui/issues/10341 是同一个问题，即

> I got this error when using a Popover inside my Dialog with focus on an Input, i found this issue by google and solved it by adding disableEnforceFocus when the input was focused and the Popover is visible, I think this issue is enough 👍

如果猜想正确，在 https://github.com/UniqueStudio/UniqueRecruitmentDashboard/blob/cdda9ff924865375d1ca0dc185b81603d78ae748/src/views/Candidates.tsx#L73 加上 `disableEnforceFocus` 即可以解决

**Comment by winderica** [comment]
感谢反馈。
我好久没维护了，之后会bump一下依赖版本（虽然记得这个问题之前修过

**Comment by winderica** [comment]
发现在[这里](https://github.com/UniqueStudio/UniqueRecruitmentDashboard/blob/cdda9ff924865375d1ca0dc185b81603d78ae748/src/components/Modal/index.tsx#L21)已经修过了，只是还没部署。

**Comment by ManiaciaChao** [comment]
看起来我们需要重新部署一下CI
