### ISSUE TITLE
style missing due to dark mode

### ISSUE THREAD

**Issue by colinaaa** [UniqueStudio/UniqueRecruitmentDashboard#20]
most of the styles are created by `useStyles({ ... })` like:

https://github.com/UniqueStudio/UniqueRecruitmentDashboard/blob/31bc9c7f66b42f87bd904d1d39666d4f9315d562/src/components/Card/index.tsx#L46

and small fragments of components are wrapped with `useMemo` like:

https://github.com/UniqueStudio/UniqueRecruitmentDashboard/blob/31bc9c7f66b42f87bd904d1d39666d4f9315d562/src/components/Card/index.tsx#L91-L101

that's fine when fragments are so simple which will never change.

but now, the styles of these fragments will change when switching between light mode and dark mode,
which leads to missing styles.

will add class names to deps of `useMemo` as a fix.

any problems related to styles can be list below, I will try to fix them someday.

**Comment by colinaaa** [comment]
icons in the menu

<img width="109" alt="QQ20200919-0" src="https://user-images.githubusercontent.com/40660121/93669214-13729880-fac5-11ea-8161-d248cf7fc1d8.png">

/cc @ttzztztz

**Comment by ManiaciaChao** [comment]
> icons in the menu
> 
> <img alt="QQ20200919-0" width="109" src="https://user-images.githubusercontent.com/40660121/93669214-13729880-fac5-11ea-8161-d248cf7fc1d8.png">
> 
> /cc @ttzztztz

I'll take a look into this.

**Comment by colinaaa** [comment]
ping @ManiaciaChao

**Comment by ManiaciaChao** [comment]
> ping @ManiaciaChao

pong，周二考完ICS就来

**Comment by colinaaa** [comment]
> > icons in the menu
> 
> > 
> 
> > <img alt="QQ20200919-0" width="109" src="https://user-images.githubusercontent.com/40660121/93669214-13729880-fac5-11ea-8161-d248cf7fc1d8.png">
> 
> > 
> 
> > /cc @ttzztztz
> 
> 
> 
> I'll take a look into this.

这个我修复了 是mui版本的问题，老版本写死了background color
有时间看一下checkbox checked时候的样式吧
