### ISSUE TITLE
Errors in downloading resumes

### ISSUE THREAD

**Issue by colinaaa** [UniqueStudio/UniqueRecruitmentDashboard#25]
https://github.com/UniqueStudio/UniqueRecruitmentBackend/issues/21 中提到的问题可能是前端问题

另外，在iOS中也会有一点问题，文件会自动被加上后缀，来自： @MacsedProtoss 
设备信息：iOS 14 Safari （然而我也是iOS 14 + Safari 却无法复现）

![image](https://user-images.githubusercontent.com/40660121/94813112-2d4b9e00-042a-11eb-828d-02c09fe14f13.png)

**Comment by winderica** [comment]
它本来是个zip，MIME类型是`application/zip`，epub是`application/epub+zip`

但是理论上后缀不是浏览器加的，是前端加的，响应的`Content-Disposition`里，文件名是`5Y+y5Zyj5LmFIC0gQUlTY29yZS56aXA=`，在base64解码后后缀就是zip（

**Comment by winderica** [comment]
既没法复现，又不知道具体的原因，所以我倾向于是Safari的问题
