### ISSUE TITLE
Unable to open candidate profile after moving candidate cards

### ISSUE THREAD

**Issue by DragoonKiller** [UniqueStudio/UniqueRecruitmentDashboard#8]
Also, moving seems to be failed.

**Comment by winderica** [comment]
请问首页版本号是多少？
还有，就不要一次性开那么多issue了。

**Comment by DragoonKiller** [comment]
@winderica 1.2.8
那我一天提一个? issue不就是这么用的么, 方便你们track(

**Comment by winderica** [comment]
您好，由于后端近日的改动，组别等信息已经无法再自己设置了，而是在注册时就已经分配好。这是导致issue #5 #6 #8的原因。
至于issue #7，聊天室组件之后会改成另一种样式，现在只是暂时的解决方案。
![image](https://user-images.githubusercontent.com/13536040/47327158-9e12a900-d69e-11e8-9ef1-aa8fb0d01d3c.png)
查数据库显示，您从注册以来，根本没有选择自己的组别，也就意味着您在招新过程中完全没有使用过dashboard，那是否能做出您完全没有关注过招新的判断呢？
另一方面，关于issue的问题，我的意思是让您先整理一下，并不是不让您一次性提那么多个。同时，tracking我们是在 #1 中做的，您如果认为您的issue有tracking的价值，不妨参考一下它的格式。

**Comment by DragoonKiller** [comment]
@winderica 实际上我从招新开始从头到尾都在尝试更改但是都是失败的, 我在熬测之前也给sjm演示过.
如果你怀疑我完全没关注过招新, 我自认为在各个选手下方的评论还是挺多的, 包括对luojia的评论和各oi选手的noi系列赛报分, 您对此毫无了解我是否能做出您完全没有关注过招新的判断呢?
在一个issue里面做tracking的问题在于对github搜索的支持会差一些.

**Comment by winderica** [comment]
1. 既然一直都更改失败，那为什么不早说呢
2. 如果您对“关注”的定义是发表评论的话，那我确实没有怎么“关注”过招新
3. 参见 [projects](https://github.com/orgs/UniqueStudio/projects)，请。

不再回复。

**Comment by DragoonKiller** [comment]
@winderica 
1. 这个问题早就有人提过了, 你们当时给的解决方案是"所有地方都得是dirty". 你们又没有issue作记录, 我也没发现你们在群里有说明, 所以我默认你们知道这个bug并且没修.
2. 抱歉不是, 关注招新包括了关注评论, 但是不包括关注dashboard的开发.
3. 不知道您想表达什么.

支持继续回复.
