### ISSUE TITLE
Other login method?

### ISSUE THREAD

**Issue by DragoonKiller** [UniqueStudio/UniqueRecruitmentDashboard#9]
The Wechat login method is just ANNOYING. It's nice to have a username-password login method which can be simply recorded by browser.

**Comment by farawaaay** [comment]
我认为这是一种退步，通过账号密码登陆相当于重新启用了新的用户系统而和企业微信脱节，较为不利于管理，而且现在浏览器会记住登录状态，短时间内不需要每次都登陆。

**Comment by DragoonKiller** [comment]
@farawaaay 在这个地方使用企业微信到底有什么好处....
